name: Check Python version

on: [push]

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get key value from JSON file
      id: get-key-value-json
      uses: christiangda/gha-python-code/read-key@main
      with:
        file: test-file.json
        key: 'ID'

    - name: Output JSON key value
      run: |
        echo "The value of the key is ${{ steps.get-key-value-json.outputs.value }}"

    - name: Get key value from YAML file
      id: get-key-value-yaml
      uses: christiangda/gha-python-code/read-key@main
      with:
        file: test-file.yaml
        key: 'ID'

    - name: Output YAML key value
      run: |
        echo "The value of the key is ${{ steps.get-key-value-yaml.outputs.value }}"